# Generated by Django 2.1.1 on 2018-11-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Registerasdonar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('dob', models.DateField(max_length=8)),
                ('weight', models.IntegerField()),
                ('full_name1', models.CharField(max_length=100)),
                ('query_subject', models.TextField()),
                ('email_id1', models.EmailField(max_length=254)),
                ('mobile_no', models.IntegerField()),
                ('city', models.TextField()),
            ],
        ),
    ]
