# Generated by Django 2.1.1 on 2018-11-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerasdonar', '0002_auto_20181121_2253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Clientc',
        ),
        migrations.DeleteModel(
            name='Clientv',
        ),
        migrations.DeleteModel(
            name='Donate_blood',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Your_bloodgroup',
        ),
        migrations.AddField(
            model_name='registerasdonar',
            name='blood_group',
            field=models.CharField(choices=[('A Positive', 'A+'), ('A Negative', 'A-'), ('A Unknown', 'A'), ('B Positive', 'B+'), ('B Negative', 'B-'), ('B Unknown', 'B'), ('AB Positive', 'AB+'), ('AB Negative', 'AB-'), ('AB Unknown', 'AB'), ('O Positive', 'O+'), ('O Negative', 'O-'), ('O Unknown', 'O'), ('Unknown', 'Unknown')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='registerasdonar',
            name='city',
            field=models.CharField(blank=True, choices=[('Ahmedabad', 'ahemdabad'), ('Banglore', 'banglore'), ('Chandigarh', 'chandigarh'), ('Chennai', 'chennai'), ('Delhi', 'delhi'), ('Gurgaon', 'gurgaon'), ('Kolkatta', 'kolkatta'), ('Mumbai', 'mumbai'), ('Pune', 'pune'), ('Noida', 'noida')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registerasdonar',
            name='donate_blood',
            field=models.CharField(choices=[('Yet to denote', 'Yet_To_Donate'), ('Regular Basis', 'Regular_Basis'), ('On need', 'On_need')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='registerasdonar',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='registerasdonar',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='registerasdonar',
            name='res_phoneno',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
