# Generated by Django 2.1.1 on 2018-11-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerasdonar', '0003_auto_20181122_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerasdonar',
            name='donate_blood',
            field=models.CharField(choices=[('Yet to denote', 'Yet_To_Donate'), ('Regular Basis', 'Regular_Basis'), ('On need', 'On_need')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='registerasdonar',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=20),
        ),
    ]
