# Generated by Django 2.1.1 on 2018-11-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerasdonar', '0004_auto_20181122_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerasdonar',
            name='blood_group',
            field=models.CharField(choices=[('A Positive', 'A+'), ('A Negative', 'A-'), ('A Unknown', 'A'), ('B Positive', 'B+'), ('B Negative', 'B-'), ('B Unknown', 'B'), ('AB Positive', 'AB+'), ('AB Negative', 'AB-'), ('AB Unknown', 'AB'), ('O Positive', 'O+'), ('O Negative', 'O-'), ('O Unknown', 'O'), ('Unknown', 'Unknown')], default='Unknown', max_length=15),
        ),
        migrations.AlterField(
            model_name='registerasdonar',
            name='donate_blood',
            field=models.CharField(choices=[('Yet to denote', 'Yet_To_Donate'), ('Regular Basis', 'Regular_Basis'), ('On need', 'On_need')], default='Yet to denote', max_length=30),
        ),
        migrations.AlterField(
            model_name='registerasdonar',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=20),
        ),
    ]
