# Generated by Django 2.1.1 on 2018-11-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerasdonar', '0005_auto_20181123_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerasdonar',
            name='dob',
            field=models.DateField(default='2000-01-01', max_length=8),
        ),
        migrations.AlterField(
            model_name='registerasdonar',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
