# Generated by Django 2.1.1 on 2018-11-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='A',
            new_name='Contactus',
        ),
    ]
