# Generated by Django 2.1.1 on 2018-11-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_auto_20181107_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Ahmedabad', 'ahemdabad'), ('Banglore', 'banglore'), ('Chandigarh', 'chandigarh'), ('Chennai', 'chennai'), ('Delhi', 'delhi'), ('Gurgaon', 'gurgaon'), ('Kolkatta', 'kolkatta'), ('Mumbai', 'mumbai'), ('Pune', 'pune'), ('Noida', 'noida')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Query_subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_subject', models.CharField(choices=[('Helpline', 'help_line'), ('Marketing', 'market'), ('Other', 'other')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='city',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='query_subject',
        ),
    ]
