# Generated by Django 2.1.1 on 2018-11-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_auto_20181121_2253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Query_subject',
        ),
        migrations.AddField(
            model_name='contactus',
            name='city',
            field=models.CharField(blank=True, choices=[('Ahmedabad', 'ahemdabad'), ('Banglore', 'banglore'), ('Chandigarh', 'chandigarh'), ('Chennai', 'chennai'), ('Delhi', 'delhi'), ('Gurgaon', 'gurgaon'), ('Kolkatta', 'kolkatta'), ('Mumbai', 'mumbai'), ('Pune', 'pune'), ('Noida', 'noida')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='query_subject',
            field=models.CharField(blank=True, choices=[('Helpline', 'help_line'), ('Marketing', 'market'), ('Other', 'other')], max_length=1, null=True),
        ),
    ]
