# Generated by Django 2.1.1 on 2018-11-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0004_auto_20181122_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='city',
            field=models.CharField(blank=True, choices=[('Ahmedabad', 'ahemdabad'), ('Banglore', 'banglore'), ('Chandigarh', 'chandigarh'), ('Chennai', 'chennai'), ('Delhi', 'delhi'), ('Gurgaon', 'gurgaon'), ('Kolkatta', 'kolkatta'), ('Mumbai', 'mumbai'), ('Pune', 'pune'), ('Noida', 'noida')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='query_subject',
            field=models.CharField(blank=True, choices=[('Helpline', 'help_line'), ('Marketing', 'market'), ('Other', 'other')], max_length=50, null=True),
        ),
    ]
