# Generated by Django 2.1.1 on 2018-12-01 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0006_auto_20181123_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ('-full_name',)},
        ),
    ]
