# Generated by Django 2.1.1 on 2018-12-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0007_auto_20181201_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={},
        ),
        migrations.AlterModelTable(
            name='contactus',
            table='contactus',
        ),
    ]
