# Generated by Django 2.1.1 on 2018-11-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestblood', '0002_auto_20181121_2253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bloodgroup',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='requestblood',
            name='blood_group',
            field=models.CharField(choices=[('A Positive', 'A+'), ('A Negative', 'A-'), ('A Unknown', 'A'), ('B Positive', 'B+'), ('B Negative', 'B-'), ('B Unknown', 'B'), ('AB Positive', 'AB+'), ('AB Negative', 'AB-'), ('AB Unknown', 'AB'), ('O Positive', 'O+'), ('O Negative', 'O-'), ('O Unknown', 'O'), ('Unknown', 'Unknown')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='requestblood',
            name='city',
            field=models.CharField(choices=[('Ahmedabad', 'ahemdabad'), ('Banglore', 'banglore'), ('Chandigarh', 'chandigarh'), ('Chennai', 'chennai'), ('Delhi', 'delhi'), ('Gurgaon', 'gurgaon'), ('Kolkatta', 'kolkatta'), ('Mumbai', 'mumbai'), ('Pune', 'pune'), ('Noida', 'noida')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='requestblood',
            name='contact_no',
            field=models.CharField(default='', max_length=12),
        ),
    ]
