# Generated by Django 2.1.1 on 2018-11-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestblood', '0004_auto_20181123_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestblood',
            name='when_required',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
    ]
